"""
Report Generator
Auto-generates professional red team reports from scanner/harness JSON findings.

Input: JSON findings from atlas_scanner or red_team_harness
Output: HTML report with ATLAS matrix visualization + OWASP risk heat map
        or Markdown report for documentation systems

Usage:
    python generate_report.py --input findings.json --output report.html
"""

import argparse
import json
from datetime import datetime
from typing import List, Dict


OWASP_CATEGORIES = [
    ("LLM01", "Prompt Injection"),
    ("LLM02", "Sensitive Info Disclosure"),
    ("LLM03", "Supply Chain"),
    ("LLM04", "Data & Model Poisoning"),
    ("LLM05", "Improper Output Handling"),
    ("LLM06", "Excessive Agency"),
    ("LLM07", "System Prompt Leakage"),
    ("LLM08", "Vector & Embedding Weaknesses"),
    ("LLM09", "Misinformation"),
    ("LLM10", "Unbounded Consumption"),
]

SEVERITY_COLORS = {
    "CRITICAL": "#ff4444",
    "HIGH": "#ff8800",
    "MEDIUM": "#ffcc00",
    "LOW": "#88cc00",
    "INFO": "#0088cc",
}


class ReportGenerator:
    def __init__(self, findings: List[Dict]):
        self.findings = findings
        self.generated = datetime.utcnow().isoformat()

    def generate_html(self, target: str = "Unknown") -> str:
        summary = self._build_summary()
        owasp_heat = self._build_owasp_heatmap()
        finding_rows = self._build_finding_rows()

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Adversarial AI Red Team Report</title>
<style>
  :root {{
    --bg: #0d1117; --surface: #161b22; --border: #30363d;
    --text: #c9d1d9; --muted: #8b949e; --accent: #58a6ff;
    --teal: #20808d;
  }}
  body {{ font-family: 'Trebuchet MS', sans-serif; background: var(--bg); color: var(--text); margin: 0; padding: 2rem; }}
  h1 {{ color: var(--accent); font-size: 2rem; margin-bottom: 0.25rem; }}
  h2 {{ color: #79c0ff; border-bottom: 1px solid var(--border); padding-bottom: 0.5rem; margin-top: 2rem; }}
  .meta {{ color: var(--muted); font-size: 0.9rem; margin-bottom: 2rem; }}
  .stats {{ display: flex; gap: 1rem; flex-wrap: wrap; margin: 1.5rem 0; }}
  .stat {{ background: var(--surface); border: 1px solid var(--border); border-radius: 8px;
           padding: 1rem 1.5rem; text-align: center; min-width: 100px; }}
  .stat-num {{ font-size: 2.5rem; font-weight: bold; }}
  .stat-label {{ font-size: 0.7rem; color: var(--muted); text-transform: uppercase; letter-spacing: 0.05em; }}
  .heatmap {{ display: grid; grid-template-columns: repeat(5, 1fr); gap: 0.5rem; margin: 1rem 0; }}
  .heatmap-cell {{ background: var(--surface); border: 1px solid var(--border); border-radius: 6px;
                   padding: 0.75rem; font-size: 0.8rem; text-align: center; }}
  .heatmap-cell.has-findings {{ border-color: #ff8800; background: rgba(255,136,0,0.1); }}
  .heatmap-cell .count {{ font-size: 1.5rem; font-weight: bold; color: #ff8800; }}
  table {{ width: 100%; border-collapse: collapse; margin: 1rem 0; font-size: 0.9rem; }}
  th {{ background: var(--surface); color: var(--muted); text-align: left; padding: 0.75rem; font-weight: 600; }}
  td {{ padding: 0.6rem 0.75rem; border-bottom: 1px solid var(--border); vertical-align: top; }}
  code {{ background: var(--surface); padding: 2px 6px; border-radius: 4px; font-size: 0.8em; font-family: Consolas, monospace; }}
  .sev {{ font-weight: bold; font-size: 0.75rem; padding: 2px 8px; border-radius: 4px; }}
</style>
</head>
<body>
<h1>Adversarial AI Red Team Report</h1>
<div class="meta">
  Target: <code>{target}</code> &nbsp;|&nbsp; Generated: {self.generated} &nbsp;|&nbsp;
  Framework: MITRE ATLAS v5.4.0 + OWASP LLM Top 10 2025
</div>

<h2>Executive Summary</h2>
<div class="stats">
  <div class="stat"><div class="stat-num">{summary['total']}</div><div class="stat-label">Total Findings</div></div>
  <div class="stat"><div class="stat-num" style="color:#ff4444">{summary.get('CRITICAL',0)}</div><div class="stat-label">Critical</div></div>
  <div class="stat"><div class="stat-num" style="color:#ff8800">{summary.get('HIGH',0)}</div><div class="stat-label">High</div></div>
  <div class="stat"><div class="stat-num" style="color:#ffcc00">{summary.get('MEDIUM',0)}</div><div class="stat-label">Medium</div></div>
  <div class="stat"><div class="stat-num" style="color:#88cc00">{summary.get('LOW',0)}</div><div class="stat-label">Low</div></div>
</div>

<h2>OWASP LLM Top 10 Coverage</h2>
<div class="heatmap">{owasp_heat}</div>

<h2>Findings</h2>
<table>
<thead><tr><th>Severity</th><th>OWASP</th><th>ATLAS</th><th>Finding</th><th>Remediation</th></tr></thead>
<tbody>{finding_rows}</tbody>
</table>

<footer style="margin-top:3rem;color:var(--muted);font-size:0.8rem;border-top:1px solid var(--border);padding-top:1rem;">
  Generated by <a href="https://github.com/zestor/atlas-llm-redteam" style="color:var(--accent)">atlas-llm-redteam</a>
  — MITRE ATLAS v5.4.0 | OWASP LLM Top 10 2025
</footer>
</body></html>"""

    def generate_markdown(self, target: str = "Unknown") -> str:
        summary = self._build_summary()
        lines = [
            "# Adversarial AI Red Team Report",
            f"**Target:** {target}  ",
            f"**Generated:** {self.generated}  ",
            f"**Framework:** MITRE ATLAS v5.4.0 + OWASP LLM Top 10 2025",
            "",
            "## Summary",
            f"- Total findings: {summary['total']}",
            f"- Critical: {summary.get('CRITICAL', 0)}",
            f"- High: {summary.get('HIGH', 0)}",
            f"- Medium: {summary.get('MEDIUM', 0)}",
            f"- Low: {summary.get('LOW', 0)}",
            "",
            "## Findings",
            "",
            "| Severity | OWASP | ATLAS | Finding | Remediation |",
            "|---|---|---|---|---|",
        ]
        for f in sorted(self.findings, key=lambda x: ["CRITICAL","HIGH","MEDIUM","LOW","INFO"].index(x.get("severity","INFO"))):
            lines.append(
                f"| **{f.get('severity','')}** | {f.get('owasp_category','')} | "
                f"`{f.get('atlas_technique','')}` | {f.get('finding','')} | {f.get('remediation','')} |"
            )
        return "\n".join(lines)

    def _build_summary(self) -> Dict:
        s = {"total": len(self.findings)}
        for f in self.findings:
            sev = f.get("severity", "INFO")
            s[sev] = s.get(sev, 0) + 1
        return s

    def _build_owasp_heatmap(self) -> str:
        counts = {}
        for f in self.findings:
            cat = f.get("owasp_category", "")
            counts[cat] = counts.get(cat, 0) + 1

        cells = ""
        for cat, label in OWASP_CATEGORIES:
            count = counts.get(cat, 0)
            cls = "heatmap-cell has-findings" if count else "heatmap-cell"
            cells += f'<div class="{cls}"><div class="count">{count}</div><div>{cat}</div><div style="font-size:0.7rem;color:#8b949e">{label}</div></div>'
        return cells

    def _build_finding_rows(self) -> str:
        severity_order = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3, "INFO": 4}
        sorted_findings = sorted(self.findings, key=lambda f: severity_order.get(f.get("severity", "INFO"), 4))
        rows = ""
        for f in sorted_findings:
            sev = f.get("severity", "INFO")
            color = SEVERITY_COLORS.get(sev, "#666")
            rows += f"""<tr>
            <td><span class="sev" style="color:{color};border:1px solid {color}">{sev}</span></td>
            <td><code>{f.get('owasp_category','')}</code></td>
            <td><code>{f.get('atlas_technique','')}</code></td>
            <td>{f.get('finding','')}</td>
            <td>{f.get('remediation','')}</td>
            </tr>"""
        return rows


def main():
    parser = argparse.ArgumentParser(description="Generate adversarial AI red team reports")
    parser.add_argument("--input", required=True, help="JSON findings file")
    parser.add_argument("--output", required=True, help="Output report file (.html or .md)")
    parser.add_argument("--target", default="Unknown", help="Target system name/URL")
    parser.add_argument("--format", choices=["html", "markdown", "atlas"], default="html")
    args = parser.parse_args()

    with open(args.input) as fh:
        data = json.load(fh)

    findings = data if isinstance(data, list) else data.get("findings", [])
    target = args.target or data.get("target", "Unknown")

    gen = ReportGenerator(findings)

    if args.output.endswith(".md") or args.format == "markdown":
        content = gen.generate_markdown(target)
    else:
        content = gen.generate_html(target)

    with open(args.output, "w") as fh:
        fh.write(content)
    print(f"[+] Report written to {args.output}")


if __name__ == "__main__":
    main()
